# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robust', '0002_task_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='traceback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='traceback',
            field=models.TextField(null=True),
        ),
    ]
