# Generated by Django 4.1.3 on 2022-11-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robust", "0004_delete_ratelimitrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="payload",
            field=models.JSONField(),
        ),
    ]
